version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: inventory-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory-db
    ports:
      - "5432:5432"
    volumes:
      - inventory_db_data:/var/lib/postgresql/data

volumes:
  inventory_db_data: